In [6]:
'''
DESCRIPTION:

A Practical Usage of Numpy library and their 
functions description
'''

import numpy as np

c = np.array(range(12),float)
print(c)
print(c.shape)
print('---')
c = c.reshape((2,6))
print(c)
print(c.shape)



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
(12,)
---
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
(2, 6)


In [8]:
c.fill(0)  #fills the whole array with single value
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
c.transpose()   # creates the transpose of the array


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
c.flatten()   #Flattenes the whole array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#Concatinate of 2 or more array
m=np.array([1,2],float)
n=np.array([3,4,5,6],float)
p=np.concatenate((m,n))
print(p)

[1. 2. 3. 4. 5. 6.]


In [14]:
#'newaxis' : to increase the dimensionality of the array
q=np.array([1,2,3],float)
q[:,np.newaxis].shape


(3, 1)

In [15]:
a1=np.array([[1,2],[3,4],[5,6]],float)
a2=np.array([-1,3],float)
print(a1+a2)

[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [16]:
a3 = np.array([[0,2],[3,-1],[3,5]],float)
print(a3.mean(axis=0)) #mean of elements column-wise
print(a3.mean(axis=1))  #mean of elements row-wise


[2. 2.]
[1. 1. 4.]


In [17]:
a4 = np.array([1,3,0],float)
np.where(a!=0,1/a,a)


array([1.   , 0.25 , 0.2  , 0.125])

In [18]:
# to generate random number of varied length
#NumPy uses Mersenne Twister algorithm to generate pseudorandom number
np.random.rand(2,3)

array([[0.52250103, 0.93916351, 0.17012399],
       [0.5344115 , 0.56196827, 0.93842502]])